# Generated by Django 3.2.9 on 2021-12-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scannergoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignmentSubmission',
            new_name='PicSubmission',
        ),
    ]
