# Generated by Django 3.2.9 on 2021-12-07 15:49

from django.db import migrations, models
import django.utils.timezone
import scannergoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('scannergoapp', '0002_rename_assignmentsubmission_picsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picsubmission',
            name='file',
        ),
        migrations.AddField(
            model_name='picsubmission',
            name='Code',
            field=models.FileField(default=django.utils.timezone.now, upload_to=scannergoapp.models.content_file_name2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picsubmission',
            name='Pic',
            field=models.FileField(default=0, upload_to=scannergoapp.models.content_file_name),
            preserve_default=False,
        ),
    ]
