# Generated by Django 3.2.9 on 2021-12-08 11:45

from django.db import migrations, models
import scannergoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('scannergoapp', '0003_auto_20211207_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picsubmission',
            name='Pic',
            field=models.ImageField(upload_to=scannergoapp.models.content_file_name),
        ),
    ]
